services:
  - type: web
    name: Rajat_Resume
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - fromGroup: Rajat_resume
      - key: NODE_ENV
        value: production
        sync: true
