services:
  - type: web
    name: Rajat_Resume
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - fromGroup: Rajat_resume
      - key: NODE_ENV
        value: production

envVarGroups:
  - name: Rajat_resume
    envVars:
      - key: RESEND_API_KEY
        value: re_f7uZr3GM_HUVr7jQrW85Dn6bE3PAviHKs
