envGroups:
  - name: Rajat_resume
    envVars:
      - key: RESEND_API_KEY
        value: rnd_1hoatAvq551IklaBkAF5Y9pYvvCV

services:
  - type: web
    name: Rajat_Resume
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - fromGroup: Rajat_resume
      - key: NODE_ENV
        value: production
        sync: false
